line-length = 120

[format]
quote-style = "single"

[lint]
select = ["ALL"]
ignore = ["D100", "D101", "D102", "D105", "D106", "D107", "D212"]

[lint.flake8-quotes]
inline-quotes = "single"
